name: CI/CD to CRC

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: flask-crc-app
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  CRC_OC_TOKEN: ${{ secrets.CRC_OC_TOKEN }}
  CRC_OC_SERVER: ${{ secrets.CRC_OC_SERVER }}

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t $DOCKER_USER/$IMAGE_NAME:latest .

    - name: Login to Docker Hub
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Push to Docker Hub
      run: docker push $DOCKER_USER/$IMAGE_NAME:latest

    - name: Login to CRC
      run: oc login --token=$CRC_OC_TOKEN --server=$CRC_OC_SERVER

    - name: Deploy to CRC
      run: |
        oc project myproject
        oc delete all -l app=flask-crc-app || true
        oc new-app docker.io/$DOCKER_USER/$IMAGE_NAME:latest --name=flask-crc-app
        oc expose svc/flask-crc-app
